### ISSUE TITLE
5.0 roadmap

### ISSUE THREAD

**Issue by TrySound** [TrySound/rollup-plugin-uglify#49]
- [x] change `transformBundle` hook to `renderChunk`
- [x] rename `sourceMap` option to `sourcemap` to be consistent with rollup api
- [x] forbid using `sourceMap` as unknown option
- [x] add [worker](https://github.com/facebook/jest/tree/master/packages/jest-worker) to process each chunk in separate threads
- [ ] make same changes in terser
- [x] add points in readme
